version: '3.8'

services:
  collabhub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/collabhub?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - collabhub-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: collabhub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - collabhub-network

networks:
  collabhub-network:
    driver: bridge

volumes:
  db_data: